---
server:
  port: 8086
  contextPath: /SpringBootTaskAssignment
---
spring:
  profiles: local, default
datasource:
  taskassignapp:
    url: jdbc:h2:~/taskAssignment
    username: SA
    password:
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect
---
spring:
  profiles: prod
datasource:
  taskassignapp:
    url: jdbc:mysql://localhost:3306/world
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect

